### PR TITLE
Fix: squid:S1118, Utility classes should not have public constructors

### PR DESCRIPTION
**Pull request by elkfrawy-df**
This pull request is focused on resolving occurrences of Sonar rule 
 squid:S1118 - “Utility classes should not have public constructors ”. 
 You can find more information about the issue here: 
 https://dev.eclipse.org/sonar/rules/show/squid:S1118

Please let me know if you have any questions.
Ayman Elkfrawy.

### CODE REVIEW

**Comment by haifengl** [comment]
Many changes here are wrong. For example, for all validation and hash functions, we should be able to create instances and pass to other functions, which we do use in practice.

**Comment by elkfrawy-df** [comment]
@haifengl I can't see any good use of that. Why would you create an object of such utility class and pass it around?

**Comment by haifengl** [comment]
For model validation, we have several `test` functions in scala that take model validation objects. It is up to the users to decide which measure to use.

**Comment by haifengl** [comment]
Similarly for all classes for sort, BIC, etc. We provide static functions so that people can call them directly without create an object. But it is also possible for user to decide which measure to use. For example, in a GUI/web application, the user can drag and drop measures to test model. In that case, we need to create objects.

**Comment by elkfrawy-df** [comment]
Well if you have specific usage for such classes that is fine. But as a general practice, it is better for utility classes to be passed as class not as an object, specially there is no any polymorphism or inheritance there.

**Comment by haifengl** [comment]
I think that many classes are more complicated than adding a private constructor. There are more space to improve. For example, we can change the methods of MulticoreExecutor.java to not static. Then we can have multiple executors in runtime, which may be useful in a large system.

Instead of merging the whole request, I will review each case, cherry pick some of your changes and manually update the code. Thanks!

**Comment by haifengl** [comment]
I cherry pick your changes. Thank you very much!

**Pull request closed without merging**
