### PR TITLE
Fix: squid:S1192, String literals should not be duplicated

### PR DESCRIPTION
**Pull request by elkfrawy-df**
This pull request is focused on resolving occurrences of Sonar rule 
 squid:S1192 - “String literals should not be duplicated”. 
 You can find more information about the issue here: 
 https://dev.eclipse.org/sonar/rules/show/squid:S1192

 Please let me know if you have any questions.
Ayman Elkfrawy.

### CODE REVIEW

**Comment by douglasArantes** [comment]
I think `static final String INVALID NUMBER OF TREES` must have the `private` modifier instead of public.

**Comment by elkfrawy-df** [comment]
So should I make all `static final String` I added to be `private`? I think it would be better.

**Comment by douglasArantes** [comment]
That's it.

**Comment by haifengl** [comment]
Thanks! More importantly, we should use -XX:+UseStringDeduplication for JVM, which is more important for runtime. I don't think that we will have millions smile model in an application. So the duplicated message strings are big issues. But when we parse data files, we usually get a lot of duplicated string tokens. So -XX:+UseStringDeduplication is very important in that use case.

BTW, is it your lint tools or IDE reorganize the import statements? I see that it always move java system import to the bottom of imports and use .*, which I don't like.

Sometimes, it is dangerous to move java system import to the end. For example, we may have same class names (e.g. smile.math.Math). Can you please turn of the import reordering and .*? Thanks!

**Comment by elkfrawy-df** [comment]
Sorry about the import problem, I modified it no to do so anymore. I will fix all imports in my pull requests.
About the string duplication, these fixes are not meant only for performance matters, it is most intended to improve maintainability. 
> constants can be referenced from many places, but only need to be updated in a single place.

**Comment by haifengl** [comment]
Thanks for updates. Can you please don't use things like

import java.awt.*

Things can be weird in case of conflict name space such as java.awt.Event and com.mycompany.calendar.Event.

As you can see, I never use import wildcard in my code. Thanks!

**Comment by elkfrawy-df** [comment]
@haifengl I will squash and resolve the conflicts

**Comment by haifengl** [comment]
@elkfrawy-df the conflict is a simple one line change (some typo fix). Can you please resolve it and I will merge the request. Thanks!

**Comment by elkfrawy-df** [comment]
@haifengl Sorry, I forgot to resolve it, I will now.

**Pull request merged**
