### PR TITLE
Fix KDTree inefficiency bug

### PR DESCRIPTION
**Pull request by lukehutch**
### Your checklist for this pull request
🚨 Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [X] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your master!
- [X] Make sure you are making a pull request against the **canary branch** (left side). Also you should start *your branch* off *our canary*. **=> There is no canary branch. Basing against master.**
- [X] Check the commit's or even all commits' message styles matches our requested structure.
- [X] Check your code additions will fail neither code linting checks nor unit test.

### Description
Fix for #491.

### CODE REVIEW

**Comment by haifengl** [comment]
Thanks. I already fixed it in v2 branch.

**Comment by lukehutch** [comment]
OK, I didn't see a commit to master, hence the PR.

**Comment by lukehutch** [comment]
What's the timeline for v2 release, approximately?

**Comment by haifengl** [comment]
I cherry picked the fix into master branch.

**Pull request closed without merging**
