### PR TITLE
Add regression random forest merging capability

### PR DESCRIPTION
**Pull request by Ajk4**
Add an option to merge two random forests into one

Example use cases:
* Build random forests on spark executors and then merge them together into one big forest on driver.
* Grow forest iteratively over time

### CODE REVIEW

**Comment by Ajk4** [comment]
Also note, that data needed for proper merge error estimation is already lost, so I am doing an weighted average (in respect to forest size) of errors from both forest

**Comment by serickso** [comment]
@Ajk4 could you provide some references for your pull request?

**Comment by Ajk4** [comment]
Hi @serickso 

I doubt that there would be a paper reference since it's a technical detail. Could you try to be more specific about what you expect?

Random forest is List of DecisionTree's. Merging two Lists of decision trees into one is something that might be (and in my case it is) very useful.

With current implementation it's not possible, since there are no constructor accepting list of decision trees.

If you don't like adding new 'merge' method what about adding public constructor accepting list of decision trees? 

That way in users code we could do something like
```
RandomForest rf1 = (...); // from some spark executor
RandomForest rf2 = (...); // from other spark executor

List<DecisionTree> allTrees = Lists.concat(rf1.getTrees(), rf2.getTrees())
RandomForest combined = new RandomForest(allTrees);
```

Now that I see it I like it more that adding `merge` function.

**Comment by Ajk4** [comment]
Some reference, in R there is `combine` function for that -> https://github.com/cran/randomForest/blob/master/man/combine.Rd

**Comment by haifengl** [comment]
I will add a combine function in scala package. This should not be in the core algorithm. Thanks.

**Comment by haifengl** [comment]
Thanks!

**Pull request merged**
