### PR TITLE
Factor out default attributes for classification and regression.

### PR DESCRIPTION
**Pull request by jovilius**
Removed some duplication. What do you think @haifengl ?

### CODE REVIEW

**Comment by jovilius** [comment]
Hi @haifengl does this PR make sense?

**Comment by haifengl** [comment]
Yes, I like the changes. I had a comment for you to change. Did you see it? Basically, I would like some function name is more meaningful than "default".

**Comment by haifengl** [comment]
I merged your commit and changed it a little bit (see the commit a72901d6d805af5d4fb83926aa6ded8e0f381d81). Thanks!

**Comment by jovilius** [comment]
Thank you @haifengl

**Pull request merged**
