### PR TITLE
add demo for Naive Bayes with Iris and add PolyaUrn model

### PR DESCRIPTION
**Pull request by rayeaster**
This PR 

- adds demo for NaiveBayes classification using Iris data set (use only 2 out of total 4 features for demo purpose)
- adds PolyaUrn model in NaiveBayes : https://en.wikipedia.org/wiki/P%C3%B3lya_urn_model

### CODE REVIEW

**Comment by rayeaster** [comment]
image

**Comment by rayeaster** [comment]
following is the training error for differnt model settings on Iris:
image

**Comment by haifengl** [comment]
Thanks!

**Comment by rayeaster** [comment]
my pleasure:)

**Pull request merged**
