### PR TITLE
Fix: squid:S2275, Printf-style format strings should not lead to unex…

### PR DESCRIPTION
**Pull request by elkfrawy-df**
"This pull request is focused on resolving occurrences of Sonar rule 
 squid:S2275 - Printf-style format strings should not lead to unexpected behavior at runtime
 You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:S2275

Please let me know if you have any questions.
Ayman Elkfrawy"

### CODE REVIEW

**Comment by haifengl** [comment]
Are all changes "\n" to "%n"? Thanks!

**Comment by elkfrawy-df** [comment]
@haifengl Yes, it is, only that replacement.

**Comment by haifengl** [comment]
My understand is "\n" is okay but "%n" is more platform independent, right?

**Comment by elkfrawy-df** [comment]
Yes exactly.

**Pull request merged**
