### PR TITLE
Refactor cv, add shuffling

### PR DESCRIPTION
**Pull request by cfga**
Added shuffling parameter for cv function -- this is the primary goal of the pr.

Also refactored parameter lists, so that first comes the data, then the model, and in the end the metrics.

### CODE REVIEW

**Comment by haifengl** [comment]
Thanks. But it is important to keep trainer as the last parameter so that we can write a code block to train the model. For example,

```
cv(x, y, 10) { (x, y) => randomForest(x,y) }
```

**Comment by cfga** [comment]
@haifengl that makes sense. What if I just swap measures and trainer?

**Comment by haifengl** [comment]
Your goal is to add `shuffle` parameter. Why do you change the signature of `loocv` and `bootstrap`? `loocv` has no shuffle and `bootstrap` must have shuffle implicitly. I understand that sometimes you don't want shuffle for cv (mostly to get same result in test). I don't understand the benefit of putting the parameters `measures`  and `trainer` in additional parentheses. 

BTW, the default value of `shuffle` should be true. It is recommended to shuffle the samples for cv.

**Comment by haifengl** [comment]
To resolve the conflict between the default value of `shuffle` and varargs `measures`, I keep the existing signatures and add new methods that take a parameter of `CrossValidation` instead of `k: Int`. So you can pass a customized `CrossValidation` with `shuffle = false`.

This should be a special case, only for test purpose. We also keep the old simple interface. I believe that it is a good balance.

**Comment by haifengl** [comment]
BTW, it is in the master branch now. Check it out.

**Pull request closed without merging**
