### PR TITLE
Loosen restriction on class labels for most classifiers so that gaps are allowed.

### PR DESCRIPTION
**Pull request by twotabbies**
This addresses #462.

### CODE REVIEW

**Comment by twotabbies** [comment]
Note that this includes the changes in #457.

**Comment by twotabbies** [comment]
Ping - is there any blocker for merging this? This is the biggest missing feature in Smile that's blocking us from rolling it out to the users of Google Earth Engine.

**Comment by haifengl** [comment]
Thanks for contribution. I just don't feel that it is necessary to change all classifiers to support sparse labels. With the utility class, the user can decide if they need to call them before the training and after the prediction. It is better to keep these two parts decoupled and keep the classifier classes simple and clean. Thanks again.

**Comment by twotabbies** [comment]
I feel it's poor API design to require users to rely on wrapper classes to get functionality that's not present in the base classes. It means that N people have to do work rather than 1 person doing work - every new user needs to rediscover the wrapper classes, write code to use them, discover where the seams show through (e.g., if you use a wrapper class for DecisionTree, the class numbers in the result of DecisionTree.dot() won't match the user's classes... and it's basically impossible to patch those up after the fact), and so on. The approach I took affects very little code in the classifier classes: in fact, most classifiers ended up *smaller* after the change.

The need for this is real - I have scientists who are waiting on this feature, and this feature alone, before they can start using the new Smile-based features of Earth Engine. Without this, we'll have to explore other options.

**Comment by haifengl** [comment]
Will the users use smile directly in Earth Engine? Not some layer built on top of it?

**Comment by twotabbies** [comment]
There are a lot of layers in between Smile and the code the users write - so there are opportunities to insert wrappers on our side and so to hide the lack of support for missing class instances. But this wouldn't actually fix the issue completely: as noted, the class labels in the output of .dot() (which would be available to users) would be incorrect. More importantly, so would the class labels in the output of .rpart() (not yet merged), which means that the output of .rpart() wouldn't be able to fulfil its primary purpose of being an interchange format. Fixing this would involve ugly and unreliable patching of the generated strings...

But the point I'm making is that as things stand, I have to write a wrapper class, which I can do... but then so does the next person, and so does any other user who has a similar issue (which is potentially a lot of people - anyone doing local research using a label set developed for global coverage).

**Comment by haifengl** [comment]
In v2, the data frame provides the freedom to use irregular class labels, such as strings, enums, etc. One may encode sparse (integer) class label with NominalScale to handle this issue.

However, there are still use cases that the users want to use the sparse integer class labels directly. I am designing a new Classifier interface to support it. Will update soon.

**Comment by twotabbies** [comment]
Thanks - it sounds like v2 will have a lot of valuable features.

**Comment by haifengl** [comment]
I have incorporate this in v2. Please check smile.classification.ClassLabel and DecisionTree, RandomForest, AdaBoost, and GradientTreeBoosting. Thanks!

**Comment by haifengl** [comment]
Close as we implement this feature in v2. Thanks

**Pull request closed without merging**
