### PR TITLE
Include variable names for OLS

### PR DESCRIPTION
**Pull request by benmccann**
Partially addresses https://github.com/haifengl/smile/issues/297. There are probably other algorithms where this would be useful as well

I implemented this with a simple `String[]`. However, it may be preferable to use a dataframe like [Tablesaw](https://github.com/jtablesaw/tablesaw) similar to Spark's dataframe. If you would like, I could send a PR to utilize a dataframe as a nicer datastructure for this information.

### CODE REVIEW

**Comment by haifengl** [comment]
We have `AttributeDataset` that provide attribute name and other info. RandomForest, for example, takes it as input.

**Comment by benmccann** [comment]
I don't think `RandomForest` does take `AttributeDataset` as input actually. I can only find tests that use `AttributeDataset`

**Comment by benmccann** [comment]
Oh, it does take `Attribute[] attributes` as input though

**Comment by benmccann** [comment]
I will update this PR this evening

**Comment by benmccann** [comment]
@haifengl thanks for the helpful pointer! I've updated this PR so that `OLS` takes an `AttributeDataset`

**Comment by haifengl** [comment]
Thanks!

**Comment by haifengl** [comment]
Unit test fails with this change. I fixed it. Please make sure to run unit tests first for PRs. Thanks.

**Comment by benmccann** [comment]
Thank you! Sorry for the breakage

**Pull request merged**
